padding: 1
end: 
divider: 
fg: "#d0d0d0"
bg: "#292929"
lines_above: 1
modules:
- type: exitcode
  show_success: true
  success_output: 
  success_fg: "#9999ff"
  success_bg: "#000000"
  failure_fg: "#ffffff"
  failure_bg: "#bb4444"
- type: cwd
  label: " %s"
  fg: "#ffffff"
  bg: "#ff6611"
  max_depth: 3
- type: git
  bg: "#ff6611"
  clean_bg: "#197820"
  dirty_bg: "#fcbf00"
  dirty_fg: "#222222"
